### ISSUE TITLE
Update Github token in .travis.yml

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#1]
@gossi since I'm not the owner of Phootwork repos, my Github token doesn't allow to push the splitted repositories. Please, could you update `.travis.yml` with your own token?

### Step by step guide (if useful) ###

1. Download and install Travis cli (you need Ruby and Ruby Gem installed on your computer)
```bash
gem install travis
```

2. Create a personal Github access token by following [these instructions](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line)

3. Encode the token with travis cli
```bash
travis encrypt GITHUB_TOKEN=paste_the_token_here
```

4.  Update our `.travis.yml` by copying the previous  generated encrypted token and pasting it [here](https://github.com/phootwork/phootwork/blob/6df1ca4e27dffdb7115e68c47e7a6245e958d39d/.travis.yml#L32)

This token'll be useful to deploy the generated api, too (I'm working on it).

**Comment by gossi** [comment]
Same here, will it do the trick, when you join the gh team I created?

**Comment by cristianoc72** [comment]
~~It doesn't work. If you get a look at travis job log https://travis-ci.org/phootwork/phootwork/jobs/567040156#L257 you can see that there is nothing before `@github.com/`. It's because I'm not the owner of the repo and Travis can't populate the `GITHUB_TOKEN` environment variable with my own token. ~~

It works!!

**Comment by gossi** [comment]
You should be able to do that now - found the button (gh is truly weird to me about all that perm stuff)
