### ISSUE TITLE
[PROPOSAL/QUESTION] LinkedList? MonoRepo contributing?

### ISSUE THREAD

**Issue by zquintana** [phootwork/phootwork#10]
This is more of a question than an issue, btw I really like the collection repo if you haven't noticed. I end up using it a lot. I was thinking of adding linked list support to the collection repo. It's essentially similar in functionality to a stack or queue, but with greater granular control. Ultimately it's more of a conceptional difference from those other patterns. I'm not sure if it fits in the collection repo for that reason. Wanted to see what you thought about adding it the repo. Do you think it fits? Another question, with the move to being a mono repo, how does one contribute?

**Comment by cristianoc72** [comment]
We should update the `README.md` with the contribution guide (see issue #2), anyway here is a summary:

- the only repository to contribute to is `phootwork/phootwork`, so clone it and submit pull requests to it
- the directory `src` contains the source and each previous single package is in its own subdir. If you want to add a new `LinkedList` collection, put it into `src/collection` directory.
- the `tests` directory contains the test suite. Each subdir is the specific test suite for each single package. So, put the tests of the new LinkedList under `tests/collection`
- Command to run a single test suite: `vendor/bin/phpunit --testsuite collection`. Command to run all the tests of all packages: `vendor/bin/phpunit`
- when the pull request will be merged, the script `bin/auto_split.sh` will split and update the monorepo into the original single packages so your contribution will be pushed also on `phootwork/collection` package.

Thank you for your contribution!

**Comment by gossi** [comment]
@zquintana there is [CONTRIBUTING.md](https://github.com/phootwork/phootwork/blob/master/CONTRIBUTING.md) now, have a look - it explains the directory structure.
