### ISSUE TITLE
Coding standard

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#11]
I'ld like to write a `.php_cs.dist` file with the rules for our own coding standard, so that our contributors can easily fix it via [php cs fixer](https://cs.symfony.com/).
Afaik the rules of our coding standard are the following:

- indentation with tabs
- PSR-4 autoload standard (one class each file)
- blank line after namespaces
- blank line at the end of the file
- blank line before return
- open brace always on the same line (for class, methods, functions, statements definitions). i.e:

```php
<?php

class FirstClass extends BaseClass {
     public function firstMethod() {
          if ($a == $b) {
          ..........
          }

          return $a;
       }
}
```
- spaces before and after operators (ok: `$foot = 'left';`, not ok: `$foot='left'`)
- lowercase for everything (true, false, null, array etc) except for class name (studly case) and property or variables (camel case). Note: lowercase also for namespaces.
- upper case for constants
- Docblock comments for classes and methods, with all php documentor tags.
- blank line after docblock description (before `@param` tags)
- no blank line between `@param` and other tags (I like blank lines before and after)
- for 2.* version: array short syntax
- for 2.* version: declare(strict_types=1) immediatly after open tag eg.:

```php
<?php declare(strict_types=1);

...................
```

Please, report oversights, mistakes and suggestions.

We could also add https://styleci.io/

**Comment by gossi** [comment]
Yes, absolutely!

I have created this not to long ago: https://github.com/gossi/php-cs-fixer-config
We can use it as a base or even better move it over to phootwork at `phootwork/php-cs-fixer-config` (from which I can reference it, too).

I like the idea of StyleCI :)

**Comment by gossi** [comment]
> no blank line between @param and other tags (I like blank lines before and after)

you mean, to delimit a group of docblock tags with blank lines?

**Comment by cristianoc72** [comment]
Yes, we have two choices:
```php
/**
 * First choice for docblock of an useful method
 *
 * @param string First parameter
 * @param int Second parameter
 * @return string The useful output
 */
```
or
```php
/**
 * Second choice for docblock of an useful method
 *
 * @param string First parameter
 * @param int Second parameter
 *
 * @return string The useful output
 */
```
I find more readable the second, but it's only my opinion.

> I have created this not to long ago: https://github.com/gossi/php-cs-fixer-config

Yeah! It's exactly what I was thinking about!

Well, StyleCI does the same work: it can check or fix the coding style, based on its configuration file  (.styleci.yml). If we plan to use StyleCI, its enogh to write our `.php_cs`, which is simply a copy-paste of https://github.com/gossi/php-cs-fixer-config/blob/master/src/Config.php.
If we plan to use your package, we can set up Trevis to do the job without StyleCI.

**Comment by gossi** [comment]
I'm fine either way regardings the docblock tags, so we can follow your style here :)

I would prefer a repo with a configuration rather then copying around a configuration over and over. I guess if StyleCI is then not needed, that's ok.

**Comment by cristianoc72** [comment]
Ok, let's go with your package! Do you want to add it to monorepo?

**Comment by gossi** [comment]
Yup, will do on the weekend now - was basically off the last week.

**Comment by gossi** [comment]
I did, see PR.

I dunno about CI integration, what's your suggestion?

**Comment by peter279k** [comment]
If possible, I can help this issue on integrating coding style check during Travis CI build.

I think we can do following works during Travis CI build:

- Running `composer scripts` command to check coding style before doing unit tests.

**Comment by gossi** [comment]
@peter279k thanks a lot. This is what happening at #14 at the moment (to have composer scripts for that - have a look over there).

Any suggestions that can be improved to get nice reporting from travis?

**Comment by peter279k** [comment]
Hi @gossi, thanks for your reply.

The PR #14 looks huge and I think my suggestions are about Travis setting enhancement.

I can review the Travis setting and create related PR after this PR is merged :).

**Comment by gossi** [comment]
@peter279k Sounds great, looking forward 😊

**Comment by gossi** [comment]
Already done and one PR still flying but landing soon. I gonna close this. For more, open another issue.
