### ISSUE TITLE
2.0 Release Plan

### ISSUE THREAD

**Issue by gossi** [phootwork/phootwork#20]
Repo is already looking really good and @cristianoc72 has done an impressive job of moving it here.

I would like to collect a list of things required to release v2.0 - I'd like to have a todo list here linked to issues.

I don't expect much after all.

**Comment by cristianoc72** [comment]
My two cents:

1. ~~Remove unused code #21~~
2. ~~Merge https://github.com/phootwork/php-cs-fixer-config/pull/1 and cleanup all the code style via `composer cs-fix`~~
3. ~~Solve issue #22~~
4. ~~Solve issue #23~~
5. Try to solve some other Scrutinizer/CodeClimate issues to improve the code quality
6. Improve the official documentation

We can fix points 5 and 6 also after the 2.0 release.

**Comment by gossi** [comment]
I agree with 5 and 6 (I made phootwork/phootwork.github.io#6) and replied to all other open issues you listed.

**Comment by peter279k** [comment]
How about static code analysis?

I know that the `Psalm` has been integrated in `composer.json` and we can use the `composer analytics` to evaluate code.

**Comment by gossi** [comment]
I'd say this is what codeclimate and scrutinizer are doing, I wonder if we need something at fingertips for that, though I'm not aganst that.

**Comment by gossi** [comment]
Just wanted to say, `phootwork` is enabled for github actions 👍

**Comment by gossi** [comment]
@cristianoc72 more PRs you have in mind or can we think about a beta/alpha? Do you want to have the new website done before the stable release?

**Comment by cristianoc72** [comment]
@gossi no more PRs by now. Imho the code is ready to 2.0 alpha/beta.

The only "one more thing" we could improve regards `lang\parts` using `$this->array`: it coud be better `$this->getArray()` with an abstract `getArray()` method declared in each trait (we did the same for Text). But we can postpone, because it doesn't involve the library public api.

The documentation site could be enough as is: the documents are terse but they give the needed information. Of course, it could be beautiful the new site with 2.0 stable, but imho it's not strictly needed.

**Comment by gossi** [comment]
I agree with you. I'm on a conference next week, so will most probably not respond but go ahead with the release 👍

**Comment by cristianoc72** [comment]
Version 2.0-alpha is out! :fireworks: :tada: :confetti_ball: 

@gossi please, change what you see fit.

**Comment by gossi** [comment]
Absolutely amazing! Really great work @cristianoc72 👍💯💪

**Comment by cristianoc72** [comment]
Thank you! Phootwork is amazing: once you try, you can no longer do without it.

**Comment by cristianoc72** [comment]
@gossi we're ready for 2.0 stable, imho. WDYT about?

**Comment by gossi** [comment]
(see next post)

**Comment by gossi** [comment]
Yes, this is also my feeling:

Only thing, is documentation but I helped out:

See these open PRs:

- https://github.com/phootwork/phootwork.github.io/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc review them, if you think there are changes needed, then do so - anyway merge them in right away

Overall I don't think I am a blocker at all for this. What is part of the release process (apart from PRs above):

- phootwork/phootwork.github.io#16
- Then phootwork/phootwork.github.io#15
- Take care of #51 
- Tag and release

Go for it!

**Comment by gossi** [comment]
Now that the new site is out, there should also be `v2.0` - you've done an incredible job here, would you also do the last bit and take the pride for the release?

**Comment by cristianoc72** [comment]
With great pleasure!

**Comment by cristianoc72** [comment]
Ladies and gentlemen, version 2.0 is out!

I'm celebrating tonight with a bottle of "Cantastorie" wine, by my friends of [Tenuta di Sticciano](http://www.tenutadisticciano.it/)! :wine_glass:

**Comment by gossi** [comment]
THIS. IS. AMAZING!

https://twitter.com/unistyler/status/1225342461792464896

I happily close this ;)
