### ISSUE TITLE
[text] Unused methods

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#21]
It seems that the following two methods are never used:
https://github.com/phootwork/phootwork/blob/1f3396e5073d4823630b2a547619aacd53ea6583/src/lang/Text.php#L1105
https://github.com/phootwork/phootwork/blob/1f3396e5073d4823630b2a547619aacd53ea6583/src/lang/Text.php#L1080

Could we remove them?

**Comment by gossi** [comment]
If unused for sure. I think I once copied them over from somewhere but didn't use them at all 🙈

**Comment by peter279k** [comment]
Can the `Psalm` detect the unused method?

I know the `phpstan` can do that, but I've no idea about `Psalm`.

Please forgive me that I'm not good at the `Psalm` static code analysis tool.

**Comment by cristianoc72** [comment]
No, Psalm can't. Good to know that phpstan can! I'll try to setup 'phpstan' too!
