### ISSUE TITLE
[file] Text or strings?

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#23]
In `phootwork\file` some methods return `string` while other return `Text` objects.
Imho we should decide between the two, to make the library more consistent.

**Comment by gossi** [comment]
True point.

A little history: iirc my idea was to make this class usable by non-phootwork methods. However, now I assume, that returning `Text` might work to have the phootwork benefits, while that code not using `Text` but just `string` the magic `Text::__toString()` will be used. If I am right, then I'd say just return `Text` and we can support both cases.

what would you suggest we should return?

**Comment by peter279k** [comment]
To be consistency, I think we can organize them to return `string` type or `Text` object.

IMHO, I prefer let them return `string` type because it can make returned types straightforward.

**Comment by cristianoc72** [comment]
Closed via #31
