### ISSUE TITLE
GitHub issue template

### ISSUE THREAD

**Issue by peter279k** [phootwork/phootwork#24]
To let contributors submit issue to have the consistency format, I think we should consider integrating the [GitHub issue templates](https://help.github.com/en/articles/creating-issue-templates-for-your-repository).

I think we can consider categorizing following items:

- Feature requests
- Bug reports

**Comment by gossi** [comment]
If this library is getting bigger and getting flodded with issues, then yes I see this can help. For now it would just be overengineering and the empty textfield is just fine. I gonna close this and if we are flooded with issues please feel free to reopen or create a new issue.
