### ISSUE TITLE
Make sub-packages readonly

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#3]
The single phootwork sub-packages repos should be marked as read-only.
This means that:

1. remove issues from repository settings
2. write `[READ-ONLY]` at the beginning  of the description
3. update `README.md` of the single sub-packages to warn that contributions and issues should be submitted to `phootwork/phootwork`

@gossi I can do it for you, but I need push permissions to single packages, too.

**Comment by gossi** [comment]
I created a team for the boths of us (send you an invite) with admin permissions to all of the repos, when you join will it do the trick?

**Comment by cristianoc72** [comment]
Done, everything works fine!

I think we should remove travis and Scrutinizer webhook from single repositories.
Which version for the monorepo? Imho 1.0. When I'll submit the new php >=7.2 pull request, that version will be 2.0

**Comment by gossi** [comment]
I agree, with all that.

**Comment by gossi** [comment]
Ah, better we release the monorepo as `v2.*` to not conflict with the existing packages (since some of them are already released as `v1.*`). (also see #8)
