### ISSUE TITLE
[collection] Bug?

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#38]
See the following example:

```php
<?php declare(strict_types=1);
require 'vendor/autoload.php';

use phootwork\collection\Queue;
use phootwork\collection\Stack;

$stackFruits = new Stack();
$stackFruits->pushAll(['apple', 'pear', 'peach', 'pine']);

$queueFruits = new Queue();
$queueFruits->enqueueAll(['apple', 'pear', 'peach', 'pine']);

echo "{$stackFruits->pop()}\n"; // return 'pine'
echo "{$queueFruits->poll()}\n"; // return 'pine'
```
If I understand what FIFO and LIFO means, `$queueFruits->poll()` should return 'apple', isn't it?

Imho the problem regards how PHP implements `array_shift` and `array_unshift` functions. I try to explain: `array_push` and `array_pop` functions work as a *stack (lifo)* on the top of the array, while `array_shift` and `array_unshift` functions work as a *stack (lifo)*, too, but at the end of the array.
So, imho, array shift /unshift are not suitable to implement a FIFO collection: we could use `array_unshift` to push onto the end and `array_pop` to pop from the top.

**Comment by gossi** [comment]
This was causing me mindfucks as well. Basically: 

- `Queue`: `array_shift` + `array_unshift`
- `Stack`: `array_push` + `array_pop`

Since `Queue` and `Stack` are syntactic sugar over these array methods, the tests must work against these methods. Equally, if I start with a `Queue` and run `$q->toArray()` I should be able to continue using the shift/unshift methods. If this is broken, then it needs a fix.

What we _should_ do, is to remove `enqueueAll()` and `pushAll()` and instead align them with the other collection methods: `enqueue(...$elements)` and `push(...$elements)`.

**Comment by cristianoc72** [comment]
So `Queue` is NOT a FIFO, but a FILO on the top of the array, instead of the end. Run the following:

- `array_push`, `array_pop`

```php
<?php declare(strict_types=1);

$array = [1, 2, 3];
array_push($array, 4);

print_r($array); // [1, 2, 3, 4]

$element = array_pop($array); 

print_r($element); // 4: OK! It's the last inserted element: it's a stack FILO
```
- `array_shift`, `array_unshift`

```php
<?php declare(strict_types=1);

$array = [1, 2, 3];
array_unshift($array, 4);

print_r($array); // [4, 1, 2, 3]

$element = array_shift($array); 

print_r($element); // 4: it's the LAST inserted element: it's a FILO, too!
```
Imho it's not the right way: we should think about what the collection are and not about the PHP functions to wrap. I try to explain myself well (despite my terrible English).

### Stack

1. **What we want to model with `Stack` class?** A classic stack: *Last in First Out* collection (or *First In Last Out* if you prefer). The *last inserted* element must be the *first retrieved*.
2. **What could be the implementation?** Given an array, I add an element to the end of the array and I retrieve an element from the end of the array.
3. **Which PHP functions could I use?** `array_push` adds an element to the end of the array, `array_pop` retrieves an element from the end of the array.

### Queue

1. **What we want to model with `Queue` class?** A classic queue: *First in First Out* collection (or *Last In Last Out* if you prefer). The *first inserted* element must be the *first retrieved*.
2. **What could be the implementation?** Given an array, I add an element to the end of the array and I retrieve an element from the top of the array.
3. **Which PHP functions could I use?** `array_push` adds an element at the end of the array, `array_shift` retrieves an element from the top of the array.

Now we have a correct (imho) implementation of Stack and Queue collections (see PR #39).

**Comment by gossi** [comment]
Yes and no 🙈

Queue: FIFO
Stack: FILO

That's for sure and the answer is: It's a matter of perspective 😱

If you `peek()` both of them, then it tells you which is the next element that will go off. For a queue this is the most left element in the array, for a stack this is the most right element in the array.

So, using `array_shift`/`array_unshift` mutate the array from the left whereas `array_push`/`array_pop` mutate the array from the right. If you always read from the left, then the first pair is FIFO and the latter is FILO.

If you also read the queue (shift/unshift) from the right, that doesn't work (which what I was trying, too). However, if you treat the arrays as I just mentioned it works. Althouth the array is an internal representation of `Queue` and `Stack`, when calling `toArray()` it still works with the existing methods php provides.

Does that work for you?

**Comment by cristianoc72** [comment]
Ok, I'm gonna close this issue and PR #39 .
New PR is on the road!

**Comment by gossi** [comment]
I hope this doesn't let stay confusion?

**Comment by cristianoc72** [comment]
Yep, I'm very confused! 🤣 And this is the opportunity, for me, to study some theory!
