### ISSUE TITLE
CI / Code Quality

### ISSUE THREAD

**Issue by gossi** [phootwork/phootwork#4]
For the past I've been using scrutinizer-ci (with travis-ci) to let it measure the code quality metrics. Shall we continue with this? Or do you have other preferences?

**Comment by cristianoc72** [comment]
Well, in my personal projects I use Codeclimate: it does the same thing as Scrutinizer and additionally it evaluates cyclomatic and cognitive complexity.
Scrutinizer is already up and running, so I could configure Codeclimate too, and make a choice later (or continue to use both).

For CI, my vote is 100% for Travis: it's easy to configure and it's rich of all sort of functionalities. I also got a try to CircleCi but its configuration is a nightmare for me (I'm not in love with Docker :smile:), even if it is almost twice faster then Travis.

**Comment by gossi** [comment]
For tests, travis is super fine 👍 

I've seen that I'm using legacy config for scrutinizer (I guess updating it gains new functionalities - not quite sure though). So that would need to be updated. I haven't used codeclimate before but it looks nice. 

I think they can run both in parallel for a time and then we can decide which one to go :D

**Comment by gossi** [comment]
I signed phootwork up for the beta of Github CI/CD ;)

**Comment by gossi** [comment]
I close this, since we have good setup already and maybe we can switch to GH in the future, that is when we have access to it.
