### ISSUE TITLE
Constructor vs Additions

### ISSUE THREAD

**Issue by gossi** [phootwork/phootwork#42]
Just spotted in the docs you send a PR for. In the queue example we have this:

```php
fruits = new Queue(['apple', 'pear', 'peach', 'pine']);
$fruits->peek(); // return 'apple'
```

We also have this:

```php
$fruits = new Queue();
$fruits->add('apple', 'pear', 'peach', 'pine');
$fruits->peek(); // ???
```

What I'm saying, that constructor and addition methods gone out of sync in terms of mechanics:

```php
fruits = new Queue(['apple', 'pear', 'peach', 'pine']);
$fruits->add('apple', 'pear', 'peach', 'pine');
```

first time an array, second time a "spread array". It is a php5 articfact carried over.

What about something like this constructor:

```php
class Queue {
	constructor(...$elements) {
		$this->enqueue(...$elements);
	}
}
```

For `Map` it must stay as is.

It's tricky, WDYT?

**Comment by cristianoc72** [comment]
Yep, `Queue` constructor is buggy (PR'll arrive asap).

I prefer to maintain the current constructor notation: imho it makes sense to create a collection starting from an array, that sometimes could come from another function; in the end, our collections are wrappers around arrays, aren't they?

`Queue' constructor could be modified as:

```php
class Queue {
	constructor(array $elements = []) {
		$this->enqueue(...$elements);
	}
}
```

**Comment by cristianoc72** [comment]
The constructor refactored like above is not the solution: `QueueTest::testMap` fails because EVERY TIME we return a new `Queue` object the wrapped array is inverted.

**Comment by gossi** [comment]
> I prefer to maintain the current constructor notation: imho it makes sense to create a collection starting from an array, that sometimes could come from another function; in the end, our collections are wrappers around arrays, aren't they?

Yeah, I thought about this too. In the end, that's up to the consumer what he wants to do, he can still do this:

```php
$q = new Queue(...$myArrayIgotFromSomwhere);
```

It's more like leaving _them_ the choice of what they want to do. It's actually very smart because leveraging the syntax wisely, which is why I'm fine with it.

**Comment by gossi** [comment]
Giving my brain some time to sort this, I agree with you. Constructors are feeded with arrays and should be good. Keeps the syntax in sync between lists and maps.

I gonna close this
