### ISSUE TITLE
Introduce Github Actions

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#44]
I'ld like to start with Github Actions expecially for the monorepo management tasks. Imho it could simplify all the automatic operations, such as split packages, draft releases etc.

For example: as you can see, when we drafted the new 2.0-alpha release, the packages was tagged but no new release drafted. It's an operation that can be done very easily by Github Actions.

We could also create our own Actions to build api and to split the monorepo and remove the `bin` directory from the library, etc.

Suggestions?

**Comment by gossi** [comment]
Absolutely go for it! I thought so to. Make it your playground :)

**Comment by gossi** [comment]
Ref #46 - track in the PR, gonna close this one then.
