### ISSUE TITLE
Psalm errors

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#57]
New versions of Psalm raise a new type of error: `UnsafeInstantiation`. It occurs when instantiate an object from a parent class, via something like `new static` instruction, i.e. https://github.com/phootwork/phootwork/blob/77bf0e3896dc950a9a27bc0a2cbff1b332312db3/src/lang/AbstractArray.php#L45

If we're agree with Psalm, we should move this methods in each subclass (i.e. each collection'll have a `_clone` or a `create` method).
Otherwise, I'll annotate the code with a `@psalm-suppress` instruction.

Imho, I prefer to leave the code as is: I find it more elegant and less repetitive.
@gossi what do you think about?

**Comment by peter279k** [comment]
Some useful [reference](https://psalm.dev/docs/running_psalm/issues/UnsafeInstantiation) is about `UnsafeInstantiation`.

**Comment by cristianoc72** [comment]
Great, thnk you! I'll investigate and submit a PR asap.

**Comment by gossi** [comment]
I have no preference. I can also live with both ways. I gonna accept whatever PR you fire here 😂

**Comment by cristianoc72** [comment]
Closed via #58
