### ISSUE TITLE
`add()` method bug

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#64]
In https://github.com/phootwork/phootwork/blob/10ec22d337109d458c8c82dc8b55e90bdcff03a5/src/lang/parts/AddPart.php#L22

we find the index, where to insert a new element, by the instruction `count($this->array)`. But when we remove and add a new element, it's possible an overwriting of an existent element. I.e.:

```php
<?php declare(strict_types=1);

use phootwork\collection\ArrayList;

$coll = new ArrayList(['element_0']);    // the internal array is: [0 => 'element_0']

$coll->add('element_1');     //now it is [0 => 'element_0', 1 => 'element_1']
$coll->removeByIndex(0);  //now it is [1 => 'element_1']

$coll->add('element_2');   //the internal array is [1 => 'element_2']  overwriting!!
```

I can see two possible solutions:

1.  we can add a new element without setting the key: ` $this->array[] = $element;`, appending it at the end of the internal array
2. we can re-index the internal array, whenever we remove an element, so that when we do `$coll->removeByIndex(0);` the resulting internal array is `[0 => 'element_1']

Suggestions are wellcome!

**Comment by gossi** [comment]
Actually. All our lists, should be tested with the new [`array_is_list`](https://wiki.php.net/rfc/is_list) function after mutating the elements. Adding/Removing should always be `true` when using `array_is_list` afterwards.

Maybe this polyfill is of help as dev-dependency?: https://packagist.org/packages/symfony/polyfill-php81

**Comment by cristianoc72** [comment]
Great suggestion, thank you!
Adding is already safe: `add()` method ensures to put the element with the last index and `insert()` method already reorder the array after insertion. I modified the `remove()` method with `array_is_list` function, as you can see in PR #66.
