### ISSUE TITLE
[file] Write method doesn't show errors

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#69]
`phootwork\file\File::write` method say nothing if something went wrong while writing a file.
 
I.e.: if I have an existent file with no write permissions, 
https://github.com/phootwork/phootwork/blob/c4bf00ad3cb1e1e48716a54374f228e26c93321a/src/file/File.php#L57 this instruction doesn't modify it but I can't write my content. 
https://github.com/phootwork/phootwork/blob/c4bf00ad3cb1e1e48716a54374f228e26c93321a/src/file/File.php#L59 this instruction return false, but our `write` method ends silently, even if the content is not correctly written.

Imho, we should throw a `FileException` exception, if `file_put_contents` return _false_.

**Comment by gossi** [comment]
Great idea. I am wondering if there is a chance to get the reason for the error that we can put into `FileException`?

**Comment by cristianoc72** [comment]
Well, the only use case I encountered is an already existent file but not writeable.
If the entire directory isn't writeable the exception is thrown here https://github.com/phootwork/phootwork/blob/c4bf00ad3cb1e1e48716a54374f228e26c93321a/src/file/File.php#L57
If the file doesn't exists, the same line ensures it'll be created.
Anyway, as far as I can imagine it's a matter of permissions, so we could say something like this: "It's impossible to write the file: do you have enough permissions?".

**Comment by cristianoc72** [comment]
Closed via #73
