### ISSUE TITLE
[file] A method to retrieve the size of a file could be useful

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#70]
`phootwork\file\File` hasn't  a method to retrieve the file size. Imho, could be useful a `getSize` method with the following signature:

```php
<?php

public function getSize(string $scale): int
```
while `$scale` could be `b`, `Kb`, `Mb` or `Gb` or something else to retrieve the size in kilobytes, megabytes etc.

**Comment by gossi** [comment]
adding a `getSize()` method is a good idea. But it should return the size in bytes. Formatting this to the desired form is the responsibility of userland code.
