### ISSUE TITLE
[file]Normalize the name of the file

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#72]
Php hasn't a "normalized" way to write paths: `/my/awesome/file.txt` is ok but (on Windows) `/my/awesome\file.txt` is ok, too. This behavior can create problems while working on Windows, if we create a `phootwork\file\File` object from (i.e.) an SplFileInfo object.
See the following example:

```php
<?php declare(strict_types=1);

$finder = new Symfony\Component\Finder\Finder();
$finder->in(...)->name(....)->files;

foreach ($finder as $fileInfo) {
    $file= new File($fileInfo->getPathName()); // on windows we have a combination of / and \ into the path name
    .....................
    
    // The following test fails on Windows
    Assert::assertStringContainsString('/my/beautiful/file.txt', $file->getPathname());
}
```
I propose to "normalize" the path name, by replacing `\` with `/` in the `phootwork\file\File::__constructor` method.

**Comment by gossi** [comment]
yeah, sounds good. Maybe can utilize `DIRECTORY_SEPARATOR` ? But dunno how 😅

**Comment by cristianoc72** [comment]
It's exaclty what I'ld like to avoid :laughing: `DIRECTORY_SEPARATOR` translates in `/` on Linux/MacOs and in `\` on Windows. So we should refactor all the tests putting DIRECTORY_SEPARATOR wherever there is `/`.

Since in PHP `/`perfectly works on all operating systems, I find useless other than standard linux paths.
