### ISSUE TITLE
Upper and lower case

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#84]
I'd like to discuss the behavior of  `Text::isLowerCase` and `Text::isUpperCase` methods.

They're are wraps around `ctype_lower` and `ctype_upper` PHP functions and they consider space characters neither lower nor upper case, so currently we have the following behavior:

```php
<?php

$lower = new Text('lower case string');
$upper = new Text('UPPER CASE STRING');

$lower->isLowerCase();  // return FALSE

$upper->isUpperCase(); // return FALSE
```
Imho, the tests in the previous example should return both true: if we have multiple words, separated by spaces, the methods should return true if each word is lower/upper case.

What's your mind about it?

**Comment by gossi** [comment]
I would consider the current implementation to be _correct_ as it is _exact_ - changing it to ignore whitespace _can_ mean an unpredicted result, but that doesn't mean your use-case is wrong.

What about something like `$text->isLowerCaseWords()`?

**Comment by cristianoc72** [comment]
> I would consider the current implementation to be _correct_ as it is _exact_

Yep, I read the`ctype_lower` documentation and you're right.

> What about something like `$text->isLowerCaseWords()`?

The idea is good but, since the behavior of `Text::isLowerCase` is correct, I don't want to add another method for that simple use case. 
Basically, I can check the case of multiword strings just by doing `$text->replace(' ', '')->isLowerCase()` :smile:
 
Thanks for the quick reply!

**Comment by gossi** [comment]
Ah yeah, what you are describing is actually better, reason:

Your original idea is _doable_ with the provided API, so it _can_ be done in userland. The inverse wouldn't be possible and also unpredictable, e.g.:

```php
<?php
$lower = new Text('lower case string');
$lower->isLowerCase(); // if this is TRUE, then
$lower->split(' ');  // returns ['lowercasestring'] ?
```

The library can stand with minimal but necessary API surface - that's good design :)
